initial_file = "file.txt"
encrypted_file = "encrypted_file.txt"
decrypted_file = "decrypted_file.txt"
symmetric_encrypt_key = "encrypt_key.txt"
public_pem = "public.pem"
private_pem = "private.pem"
initial_file_path = "C:/Users/lenay/OneDrive/Рабочий стол/2K4C/OIB/labs/oib_lab3/file"