initial_file = "path/to/initial/file.txt"
encrypted_file = "path/to/encrypted/file.txt"
decrypted_file = "path/to/decryptad/file.txt"
symmetric_encrypt_key = "encrypt_key.txt"
public_pem = "public.pem"
private_pem = "private.pem"